import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Key, ReactChild, ReactFragment, ReactPortal } from 'react';
import styles from '../styles/Home.module.css'

interface HomeProp {
  exchange : ExChange;
}

// interface ExChange {
//   result?: 1,
//   cur_unit?: String,
//   ttb?: String,
//   tts?: String,
//   deal_bas_r?: String,
//   bkpr?: String,
//   yy_efee_r?: String,
//   ten_dd_efee_r?: String,
//   kftc_bkpr?: String,
//   kftc_deal_bas_r?: String,
//   cur_nm?: String,
// }

interface ExChange {
  userId: number;
  id: number;
  title: string;
  completed: boolean;
}

const Home = ({ exchange }: HomeProp) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ExChangeService</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        환율내용입니다.
        <div>
          <table>
            <tr>
              <td>userId</td>
              <td>id</td>
              <td>title</td>
            </tr>
            <tr>
              <td>{exchange.userId}</td>
              <td>{exchange.id}</td>
              <td>{exchange.title}</td>
            </tr>
          </table>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
};

export async function getServerSideProps() {
    // const res = await fetch("https://www.koreaexim.go.kr/site/program/financial/exchangeJSON?authkey=coZvPjTmHHugazuTqHYxjKaYG3JKVMHs&searchdate=20180102&data=AP01");
    const res = await fetch("https://jsonplaceholder.typicode.com/todos/1");
    const exchange: ExChange = await res.json();

    return { props: { exchange } };
}

export default Home
