import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { Key, ReactChild, ReactFragment, ReactPortal } from "react";
import { Provider } from "react-redux";
import { store } from "../provider";
import styles from "../styles/Home.module.css";
import 'bootstrap/dist/css/bootstrap.css';
import Appbar from "./bar/appbar";

const Home = () => {
  return (
    <Provider store={store}>

    <div className={styles.container}>
      <Head>
        <title>ExChangeService</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Appbar />

      <main className={styles.main}>
        <h1>Lobby</h1>
      </main>

      <footer className={styles.footer}></footer>
    </div>
    </Provider>
  );
};


export default Home;

