import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Key, ReactChild, ReactFragment, ReactPortal } from "react";
import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ExChangeService</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Lobby</h1>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};


<<<<<<< HEAD
export default Home;

=======
export default Home
>>>>>>> f85b5eb79ad87bf51c8361f6b551036157df9d32
