import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Key, ReactChild, ReactFragment, ReactPortal } from 'react';
import styles from '../styles/Home.module.css';

import lobbiy from '../pages/lobby/lobbiy';
import calculator from '../pages/lobby/Calculator';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ExChangeService</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
};

export async function getServerSideProps() {
    // const res = await fetch("https://www.koreaexim.go.kr/site/program/financial/exchangeJSON?authkey=coZvPjTmHHugazuTqHYxjKaYG3JKVMHs&searchdate=20180102&data=AP01");
    const res = await fetch("https://jsonplaceholder.typicode.com/todos/1");
    const exchange: ExChange = await res.json();

    return { props: { exchange } };
}

export default Home
